// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsLboZUl4xEZ_EAeAfXWdjS9hqJaDJZkM',
    appId: '1:612216669934:web:122fcb5ed8753dee0855ff',
    messagingSenderId: '612216669934',
    projectId: 'utsav-3bbc6',
    authDomain: 'utsav-3bbc6.firebaseapp.com',
    storageBucket: 'utsav-3bbc6.firebasestorage.app',
    measurementId: 'G-RFVMNY573J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1UUiPv93n9Xvjw_kwot3e0frrFu0heGo',
    appId: '1:612216669934:android:f152179413f36ce80855ff',
    messagingSenderId: '612216669934',
    projectId: 'utsav-3bbc6',
    storageBucket: 'utsav-3bbc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkLOIuyL-8210_wNXHxQZWFmeRsXpr1ao',
    appId: '1:612216669934:ios:a87dac0db31f7ab30855ff',
    messagingSenderId: '612216669934',
    projectId: 'utsav-3bbc6',
    storageBucket: 'utsav-3bbc6.firebasestorage.app',
    iosBundleId: 'com.utsav.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkLOIuyL-8210_wNXHxQZWFmeRsXpr1ao',
    appId: '1:612216669934:ios:a87dac0db31f7ab30855ff',
    messagingSenderId: '612216669934',
    projectId: 'utsav-3bbc6',
    storageBucket: 'utsav-3bbc6.firebasestorage.app',
    iosBundleId: 'com.utsav.app',
  );
}
